language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"

os:
  - windows
  - linux
  - osx

cache: pip
sudo: required

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-mock
  - pip install -U pytest-console-scripts

install:
  - pip install -e .

script: pytest
